(() => {
'use strict';
const $ = s => document.querySelector(s);
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => {const d=new Date(value);return Number.isNaN(d.getTime())?'Date unavailable':d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'});};
const routes=[['briefing','⌂','Daily Briefing'],['alerts','△','Threats & Alerts'],['reports','▤','All Reports'],['saved','♧','Saved Stories'],['analysis','▥','Analysis'],['sources','⚒','Sources'],['about','ⓘ','About']];
let data, query='', severity='All', category='All', sort='priority', saved=[];
try {const v=JSON.parse(localStorage.getItem('cyberhead.saved')||'[]');if(Array.isArray(v))saved=v.filter(x=>typeof x==='string');} catch {}
let page=()=>routes.some(r=>r[0]===location.hash.slice(1))?location.hash.slice(1):'briefing';
const reportById=id=>data.reports.find(r=>r.id===id);
const badges=r=>`<span class="badge severity ${escape(r.severity)}">${escape(r.severity.toUpperCase())}</span><span class="badge">${escape(r.category.toUpperCase())}</span>`;
const art=r=>`<div class="art ${['mail','skull'].includes(r.image)?r.image:''}" role="img" aria-label="Pixel-art cybersecurity illustration"></div>`;
const sourceName=r=>r.sourceIds.map(id=>data.sources.find(s=>s.id===id)?.name||id).join(', ');
function card(r,featured=false){return `<article class="card ${featured?'featured':''}">${art(r)}<div><div class="meta">${badges(r)}<time datetime="${escape(r.publishedAt)}">${escape(date(r.publishedAt))}</time></div><h3>${escape(r.title)}</h3><p>${escape(r.summary)}</p><div class="actions"><span class="eyebrow">PRIORITY ${r.score}/100</span><button data-open="${escape(r.id)}">Read report →</button></div><div class="related"><button class="text-button" data-open="${escape(r.id)}">Related coverage grouped (${escape(r.relatedCount)}) →</button></div></div></article>`;}
function intro(title,subtitle){return `<div class="intro"><div><div class="eyebrow">WELCOME BACK, ANALYST</div><h1>${title}</h1><p>${escape(subtitle)}</p></div><div class="clock">${escape(date(new Date()))}<strong id="clock">${new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</strong><span class="demo">${window.CYBERHEAD_CONFIG.mode==='mock'?'SAMPLE BRIEFING':'CONNECTED TO API'}</span></div></div>`;}
function alertList(){return data.alerts.map(a=>`<div class="alert"><time>${escape(a.time)}</time><button class="text-button" data-open="${escape(a.reportId)}">${escape(a.text)}</button></div>`).join('')||'<p>No alerts available.</p>';}
function briefing(){const stories=data.briefing.reportIds.map(reportById).filter(Boolean);return intro('Your <em>Daily Briefing</em>',data.briefing.summary)+`<div class="layout"><div><div class="section-label">TOP STORY</div>${stories[0]?card(stories[0],true):'<div class="empty">No briefing available yet.</div>'}<div class="section-label">MORE TOP STORIES</div><div class="grid">${stories.slice(1).map(r=>card(r)).join('')}</div></div><aside class="rail"><section class="panel"><h2>▤ TODAY’S BRIEFING</h2>${stories.map((r,i)=>`<button class="brief-item" data-open="${escape(r.id)}"><span class="number">0${i+1}</span>${escape(r.title)}</button>`).join('')}<a class="brief-item" href="#reports"><span class="number">＋</span>More security news</a></section><section class="panel"><h2>△ RECENT ALERTS</h2>${alertList()}<a href="#alerts">View all alerts →</a></section><section class="panel"><h2>▱ SOURCES</h2><p>Trace each story back to its collected coverage.</p><span class="demo">${data.sources.length} SOURCES · ${window.CYBERHEAD_CONFIG.mode==='mock'?'DEMO':'API DATA'}</span><a class="brief-item" href="#sources">View all sources →</a></section></aside></div>`;}
function filtered(){return data.reports.filter(r=>(page()!=='saved'||saved.includes(r.id))&&(severity==='All'||r.severity===severity)&&(category==='All'||r.category===category)&&`${r.title} ${r.summary} ${r.category} ${r.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='recent'?new Date(b.publishedAt)-new Date(a.publishedAt):b.score-a.score);}
function listing(){const rows=filtered();const options=(list,current)=>list.map(v=>`<option ${v===current?'selected':''}>${escape(v)}</option>`).join('');return intro(page()==='saved'?'Saved <em>Stories</em>':'All <em>Reports</em>',page()==='saved'?'Your reading list, saved on this browser.':'Explore collected stories, ranked by threat priority.')+`<div class="toolbar"><label>Severity <select id="severity">${options(['All','Critical','High','Medium','Low'],severity)}</select></label><label>Category <select id="category">${options(['All',...new Set(data.reports.map(r=>r.category))],category)}</select></label><label>Sort <select id="sort"><option value="priority" ${sort==='priority'?'selected':''}>Priority first</option><option value="recent" ${sort==='recent'?'selected':''}>Newest first</option></select></label><span>${rows.length} reports</span><button id="reset">Reset filters</button></div><div class="grid">${rows.map(r=>card(r)).join('')}</div>${!rows.length?'<div class="empty">No matching stories. Try resetting filters or saving a report.</div>':''}`;}
function analysis(){const total=data.reports.length;return intro('Threat <em>Analysis</em>','A snapshot of the loaded reports. Demo predictions are illustrative.')+`<div class="stat-grid"><div class="panel">Collected reports<strong>${total}</strong></div><div class="panel">Critical priority<strong>${data.reports.filter(r=>r.severity==='Critical').length}</strong></div><div class="panel">Sources<strong>${data.sources.length}</strong></div></div><section class="panel"><h2>REPORTS BY SEVERITY</h2>${['Critical','High','Medium','Low'].map(s=>{const n=data.reports.filter(r=>r.severity===s).length;return `<div class="bar-row"><span>${s}</span><div class="bar" role="img" aria-label="${s}: ${n} reports"><span style="width:${total?n/total*100:0}%"></span></div><span>${n}</span></div>`;}).join('')}</section><p>Classification confidence measures the model’s certainty about a category. Priority scores indicate ranking; they are not attack probabilities.</p>`;}
function safeLink(url,label){try{const u=new URL(url);if(['https:','http:'].includes(u.protocol))return `<a href="${escape(u.href)}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`;}catch{}return `<span>${escape(label)} — no source URL supplied</span>`;}
function sources(){return intro('Intelligence <em>Sources</em>','Original sources and collection status.')+data.sources.map(s=>`<section class="panel source"><h2>${escape(s.name)}</h2><span class="badge">${escape(s.status)}</span><p>${escape(s.description)}</p>${s.url?safeLink(s.url,'Visit source'):'<span class="demo">FICTIONAL SOURCE · NO LIVE FEED</span>'}</section>`).join('')+`<section class="panel"><h2>PIPELINE STATUS</h2>${Object.entries(data.pipeline||{}).map(([k,v])=>`<p>${escape(k)}: <strong>${escape(v)}</strong></p>`).join('')}</section>`;}
function about(){return intro('About <em>Cyberhead</em>','Threats move fast. Stay one step ahead.')+`<div class="prose panel"><h2>YOUR DAILY SECURITY BRIEFING</h2><p>Cyberhead organises cybersecurity coverage into readable briefings, grouped reports and threat priorities, with access to original sources.</p><h2>HOW TO USE IT</h2><p>Start with the daily briefing, open a report to inspect its summary and extracted indicators, then save stories to revisit. Search all reports and filter by category or severity.</p><h2>CURRENT VERSION</h2><p>This frontend demonstrates the interface. In demo mode, all stories, alerts, model scores and sources are fictional. No articles are collected and no ML model runs here.</p><h2>FUTURE INTELLIGENCE PIPELINE</h2><p>The backend collector will fetch permitted sources. Backend processing can extract fields, group duplicates, run classification and ranking models, and generate a daily briefing. This interface displays the resulting API data.</p><h2>LOCAL STORAGE</h2><p>Saved report IDs are stored only in this browser. There are no user accounts or cross-device syncing in this version.</p></div>`;}
function render(){if(!data)return;const current=page();$('#nav').innerHTML=routes.map(([id,icon,label])=>`<a href="#${id}" class="${id===current?'active':''}" ${id===current?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</a>`).join('');document.title=`${routes.find(r=>r[0]===current)[2]} — CYBERHEAD`;$('#content').innerHTML=current==='briefing'?briefing():['reports','saved'].includes(current)?listing():current==='analysis'?analysis():current==='sources'?sources():current==='about'?about():intro('Threats <em>& Alerts</em>','Alerts derived from the loaded report feed.')+`<section class="panel">${alertList()}</section>`;}
function openReport(id){const r=reportById(id);if(!r)return;$('#report-content').innerHTML=`<div class="eyebrow">INTELLIGENCE REPORT</div><h2>${escape(r.title)}</h2><div class="meta">${badges(r)}</div><p>${escape(r.details)}</p><div class="detail-grid"><div class="panel">Priority score<strong>${r.score}/100</strong></div><div class="panel">Classification confidence<strong>${Math.round(r.confidence*100)}%</strong></div><div class="panel">Related coverage<strong>${escape(r.relatedCount)}</strong></div></div><h3>Summary</h3><p>${escape(r.summary)}</p><h3>Suggested review</h3><p>${escape(r.recommendation)}</p><h3>Extracted indicators</h3><p>${r.indicators.length?r.indicators.map(escape).join('<br>'):'No indicators extracted.'}</p><h3>Sources & related coverage</h3><p>${escape(sourceName(r))}</p>${r.sourceIds.map(id=>{const s=data.sources.find(x=>x.id===id);return s?`<p>${safeLink(s.url,s.name)}</p>`:'';}).join('')}<p>Grouped coverage count: ${escape(r.relatedCount)}. Linked sources are those supplied with this report.</p><p><time>Published ${escape(date(r.publishedAt))}</time></p>${window.CYBERHEAD_CONFIG.mode==='mock'?'<div class="notice">Fictional demonstration report. Scores and indicators are sample data.</div>':''}<button data-save="${escape(r.id)}">${saved.includes(r.id)?'Remove from saved':'Save story ♧'}</button>`;if(!$('#report-dialog').open)$('#report-dialog').showModal();}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open)openReport(open.dataset.open);const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;saved=saved.includes(id)?saved.filter(v=>v!==id):[...saved,id];try{localStorage.setItem('cyberhead.saved',JSON.stringify(saved));}catch{$('#status').textContent='Browser storage is unavailable. Saved stories will last only for this session.';}save.textContent=saved.includes(id)?'Remove from saved':'Save story ♧';render();}if(e.target.id==='reset'){query='';severity=category='All';sort='priority';$('#search').value='';render();}if(e.target.id==='retry')load();});
document.addEventListener('change',e=>{if(e.target.id==='severity')severity=e.target.value;else if(e.target.id==='category')category=e.target.value;else if(e.target.id==='sort')sort=e.target.value;else return;render();});
$('#search').addEventListener('input',e=>{query=e.target.value;if(!['reports','saved'].includes(page()))location.hash='reports';else render();});
$('#alerts-shortcut').onclick=()=>location.hash='alerts';$('.close').onclick=()=>$('#report-dialog').close();$('#report-dialog').addEventListener('click',e=>{if(e.target===$('#report-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
window.addEventListener('hashchange',render);$('#year').textContent=new Date().getFullYear();setInterval(()=>{if($('#clock'))$('#clock').textContent=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});},30000);
async function load(){$('#status').textContent='Loading your briefing…';try{data=await CyberheadAPI.getDashboard();$('#status').textContent='';$('#mode').textContent=window.CYBERHEAD_CONFIG.mode==='mock'?'DEMO DATA · NO LIVE MONITORING':`API DATA · UPDATED ${date(data.generatedAt)}`;render();}catch(error){$('#status').innerHTML=`Unable to load reports. ${escape(error.name==='AbortError'?'The request timed out.':error.message)} <button id="retry">Retry</button>`;}}
load();
})();
