window.CYBERHEAD_CONFIG = Object.freeze({
  mode: "api",

  apiBaseUrl: "http://127.0.0.1:8000/api",

  timeoutMs: 10000,

  // While the website is open, check the API once per minute.
  // The backend briefing itself is regenerated by the pipeline every 6 hours.
  refreshMs: 60000
});